services:
  - docker

language: python

dist: trusty
sudo: false
cache:
  pip: true

python:
  - "3.6"

branches:
  except:
    - gh-pages

git:
  depth: 1

env:
  global:
  # GH_TOKEN
  - secure: "luBonHSyXUYLGAsy+tn1dePK1vACPHOpmPxahxo3lBzCWqaLLSNYOJIyfuiBq3c7WZdv4krlW8gobygPf+zDByYYR+h6w/Qo8LJwQYj0Wd9Gzn04w+4z0owHTJZo1Ls+Zg/5SBlGIiUQ9M9hkBatygumnQ8mDdDVMJ0LwuMNshB8hSDx60ihyaHQQPomJh1rxqsG+4dNkADthHhmw53O8v6XchSx3sDkQN+bYH+uVEkWIk9EUgw+RIGr73qcofc2AZvfP5Ols7Lc5DG+wsW9NxKzvBTU2vWovuY+U4Pf+RA2CZlyHffseOBr01fvhhzSCvqorrMoNe8SumqpXzy4zZ/QB42dJ5xyRzMUgkJVk1kmPli1eQw0VQMzmlJxeSjYXeyytescRuaNM822BGwlwpxmLrx9Hwodd1fj+NvtSbNmFrthksVHLG0YTwXr5WfQdAhUE/4rXCxRiDjkLZ+I3szkLnjFWZyPTS4PapOYfHQG0m9CMQJFSddOZwFVk95KF5HquNmEcsTsMEKhJZolw2Wsg8T30Wz1iPwkHiSY/+Jea+J6KuQJjR9QnXN740HH/ZSv3JIVzCLcNtQ0TenhlkP7nKNMWKX3IS7rSg3vVHWf/QGPfKTkjxkmhBF8EvJC1p1U1TZ7+QWzGzKHtC+knmJZ3a6GX3vP2hcfrlLj9o0="
  - BUILD_TESTING=$( [[ ${TRAVIS_REPO_SLUG} =~ qgis/pyqgis ]] && [[ ${TRAVIS_EVENT_TYPE} != pull_request ]] && [[ ${TRAVIS_BRANCH} =~ ^master$ ]] && echo "false" || echo "true" )

matrix:
  include:
    - env: QGIS_VERSION_BRANCH=master

script:
  - ./scripts/ci/run-docker.sh
