on:
  schedule:
    # runs every day
    - cron: '0 0 * * *'

  push:
    branches:
      - master

  pull_request_target:
    # This event is similar to pull_request, except that it runs in the context
    # of the base repository of the pull request, rather than in the merge commit.
    # This means that you can more safely make your secrets available to the workflows
    # triggered by the pull request, because only workflows defined in the commit
    # on the base repository are run
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
    branches:
      - master

  workflow_dispatch:
    # to manually trigger the build for a given branch
    # POST /repos/qgis/pyqgis/actions/workflows/2246440/dispatches
    inputs:
      qgis_branch:
        description: 'The QGIS branch'
        required: true
        default: 'master'
      home:
        description: 'location'
        required: false


jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build PyQGIS docs
        env:
          QGIS_VERSION_BRANCH: ${{ github.event.inputs.qgis_branch || 'master' }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH: true
          RUNS_ON_CI: true
          BUILD_TESTING: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.number || false }}
        run: |
          echo "QGIS_VERSION_BRANCH: ${QGIS_VERSION_BRANCH}"
          echo "PUBLISH: ${PUBLISH}"
          echo "BUILD_TESTING: ${BUILD_TESTING}"
          ./scripts/run-docker.sh

