on:
  schedule:
    # runs every day
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      qgis_branch:
        description: 'The QGIS branch'
        required: true
        default: 'master'
      home:
        description: 'location'
        required: false


jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.docker_username }}
      DOCKER_PASSWORD: ${{ secrets.docker_password }}
    steps:
      - env:
          QGIS_VERSION_BRANCH: ${{ github.event.inputs.qgis_branch || 'master' }}
          GH_TOKEN: ${{ secrets.gh_token }}
          PUBLISH: true
          BUILD_TESTING: ${{ github.event_name == 'pull_request' && true || false }}
        run: |
          echo "QGIS_VERSION_BRANCH: ${QGIS_VERSION_BRANCH}"
          echo "PUBLISH: ${PUBLISH}"
          echo "BUILD_TESTING: ${BUILD_TESTING}"

          QGIS_BRANCH=${{ github.event.inputs.qgis_branch }}
          [[ -z ${QGIS_BRANCH} ]] && QGIS_BRANCH=master

          echo "QGIS branch ${{ github.event.inputs.qgis_branch }}!"
