on:
  schedule:
    # runs every day
    - cron: '0 0 * * *'
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
  workflow_dispatch:
    inputs:
      qgis_branch:
        description: 'The QGIS branch'
        required: true
        default: 'master'
      home:
        description: 'location'
        required: false


jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.docker_username }}
      DOCKER_PASSWORD: ${{ secrets.docker_password }}
    steps:
      - env:
          QGIS_VERSION_BRANCH: ${{ github.event.inputs.qgis_branch or 'master' }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          PUBLISH: TRUE
          BUILD_TESTING: ${{ github.event_name == 'pull_request' && 'TRUE' || 'FALSE' }}
        run: |
          QGIS_BRANCH=${{ github.event.inputs.qgis_branch }}
          [[ -z ${QGIS_BRANCH} ]] && QGIS_BRANCH=master

          echo "QGIS branch ${{ github.event.inputs.qgis_branch }}!"
