on:
  schedule:
    # runs every day
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      qgis_branch:
        description: 'The QGIS branch'
        required: true
        default: 'master'
      home:
        description: 'location'
        required: false


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "QGIS branch ${{ github.event.inputs.qgis_branch }}!"
